version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
  web:
    build: .
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env
